name: CRT 4H Alerts

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-crt-4h:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests tradingview-sdk

      - name: Run 4H CRT detector
        env:
          DISCORD_WEBHOOK_4H: ${{ secrets.DISCORD_WEBHOOK_4H }}
        run: |
          python crt_detector_4h.py

      - name: Save CRT state
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add crt_state_4h.json

          git diff --cached --quiet || git commit -m "Update 4H CRT state"

          git pull --rebase origin main

          git push
